name: Validate translations

on:
  push:
  workflow_dispatch:

jobs:
  validate_translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: yarn
    - name: Install dependencies
      run: |
        yarn install
    - name: Check translations
      run: |
          yarn run validate:translations
          cat translationIssues.txt
    - name: Add annotations
      uses: pytorch/add-annotations-github-action@master
      with:
        check_name: validate_translations
        linter_output_path: translationIssues.txt
        regex: '^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w\d+) (?<errorDesc>[\s|\w|.]*)'
        commit_sha: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
